#!/bin/bash

rm -f *.o

# Step 1 : build the C++ .o files required by the library.

CFLAGS=$1
LIBRARY=xerces-c

for item in $(ls *.cpp)
do
	g++ $CFLAGS -c -fPIC -shared $item
done

# Step 2 : build the shared library required by the binaries/examples.
g++ -fPIC -shared XMLConfig.o CppXMLConfigReader.o -o libCppConfigManager.so -lxerces-c

# First build the XMLConfigExample binary. 
g++ XMLConfigExample.cpp -o XMLConfigExample -lxerces-c -L. -lCppConfigManager

# Build the second binary.
g++ ConfigReaderExample.cpp -o ConfigReaderExample -lxerces-c -L. -lCppConfigManager

# Build the third binary.
g++ OtherStuff.cpp -o OtherStuff -lxerces-c -L. -lCppConfigManager

# Build the fourth binary.
g++ SampleTest.cpp -o SampleTest -lxerces-c -L. -lCppConfigManager
