#!/bin/bash

rm -f *.o

CFLAGS=$1
LIBRARY=xerces-c

for item in $(ls *.cpp)
do
	g++ $CFLAGS -c $item
done

# First build the XMLConfigExample binary. 
g++ $CFLAGS XMLConfigExample.cpp XMLConfig.o -o XMLConfigExample -l$LIBRARY

# Build the second binary.
g++ $CFLAGS CppXMLConfigReader.o ConfigReaderExample.o XMLConfig.o -o ConfigReaderExample -l$LIBRARY 

# Build the third binary.
g++ $CFLAGS OtherStuff.o CppXMLConfigReader.o XMLConfig.o -o OtherStuffExample -l$LIBRARY

# Build the fourth binary.
g++ $CFLAGS SampleTest.o CppXMLConfigReader.o XMLConfig.o -o SampleTest -l$LIBRARY 
