#!/bin/bash

rm -f *.o *.so XMLConfigExample ConfigReaderExample OtherStuff SampleTest

# Step 1 : build the C++ .o files required by the library.
CFLAGS=$1
LIBRARY=xerces-c

for item in $(ls *.cpp)
do
	g++ $CFLAGS -c -fPIC -shared $item
done

# Step 2 : build the shared library required by the binaries/examples.
g++ -fPIC -shared XMLConfig.o CppXMLConfigReader.o -o libCppConfigManager.so -lxerces-c

# Step 3 : Build the code examples below using the new libraries.
declare -a exampleCodeList=("XMLConfigExample.cpp" "ConfigReaderExample.cpp" "OtherStuff.cpp" "SampleTest.cpp")
libOptions="-lxerces-c -L. -lCppConfigManager"
for iterator in "${exampleCodeList[@]}"
do
   binaryItem=${iterator%.cpp}
   g++ $iterator -o $binaryItem $libOptions	
done

